version: "3.8"

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile.controller
    ports:
      - "8080:8080"
    depends_on:
      - node1
      - node2
      - node3

  node1:
    build:
      context: ./node
      dockerfile: Dockerfile.node
    environment:
      - NODE_NAME=node1
      - NODE_PORT=8080
    ports:
      - "8081:8080"

  node2:
    build:
      context: ./node
      dockerfile: Dockerfile.node
    environment:
      - NODE_NAME=node2
      - NODE_PORT=8080
    ports:
      - "8082:8080"

  node3:
    build:
      context: ./node
      dockerfile: Dockerfile.node
    environment:
      - NODE_NAME=node3
      - NODE_PORT=8080
    ports:
      - "8083:8080"